//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace disec.Areas.Seget.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextSeget : DbContext
    {
        public ContextSeget()
            : base("name=ContextSeget")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {         
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOCUMENTO> DOCUMENTO { get; set; }
        public virtual DbSet<OFPLA_PISCC> OFPLA_PISCC { get; set; }
        public virtual DbSet<OFPLA_UNIDAD> OFPLA_UNIDAD { get; set; }
        public virtual DbSet<PISCC_TEMA_PRIORIZADA> PISCC_TEMA_PRIORIZADA { get; set; }
    }
}
