//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace disec.Areas.Seget.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPLA_PISCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OFPLA_PISCC()
        {
            this.DOCUMENTO = new HashSet<DOCUMENTO>();
            this.PISCC_TEMA_PRIORIZADA = new HashSet<PISCC_TEMA_PRIORIZADA>();
        }
    
        public decimal OFPLA_PISCC_ID { get; set; }
        public Nullable<decimal> UNIDAD_ID { get; set; }
        public Nullable<decimal> ID_ESTADO { get; set; }
        public Nullable<System.DateTime> ANO_APROBACION { get; set; }
        public string NRO_ACTA_APROBACION { get; set; }
        public Nullable<decimal> COSTO_TOTAL { get; set; }
        public Nullable<decimal> ID_DIAGNOSTICO { get; set; }
        public Nullable<decimal> ID_ESTRATEGIA { get; set; }
        public Nullable<decimal> ID_FINANCIERA { get; set; }
        public Nullable<decimal> VIGENTE { get; set; }
        public Nullable<long> IDENTIFICACION_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string MAQUINA_CREACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTO { get; set; }
        public virtual OFPLA_UNIDAD OFPLA_UNIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PISCC_TEMA_PRIORIZADA> PISCC_TEMA_PRIORIZADA { get; set; }
    }
}
