//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace disec.Areas.Seget.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OFPLA_UNIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OFPLA_UNIDAD()
        {
            this.OFPLA_PISCC = new HashSet<OFPLA_PISCC>();
        }
    
        public decimal UNIDAD_ID { get; set; }
      
        public Nullable<int> UNDE_LUGAR_GEOGRAFICO { get; set; }
        public Nullable<long> IDENTIFICACION_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string MAQUINA_CREACION { get; set; }
        public Nullable<decimal> VIGENTE { get; set; }
        public Nullable<decimal> UNDE_CONSECUTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFPLA_PISCC> OFPLA_PISCC { get; set; }
    }
}
